create table applications
(
    id               int8 generated by default as identity,
    about            varchar(255),
    birth_date       date         not null,
    city             varchar(255) not null,
    course           int4,
    education_status varchar(255) not null,
    email            varchar(255) not null,
    faculty          varchar(255),
    full_name        varchar(255) not null,
    phone_number     varchar(255) not null,
    specialty        varchar(255),
    status           varchar(255) not null,
    telegram_id      varchar(255) not null,
    university       varchar(255),
    username         varchar(255) not null,
    internship_id    int8,
    primary key (id)
);
create table internships
(
    id                    int8 generated by default as identity,
    description           varchar(255),
    end_date              date         not null,
    name                  varchar(255) not null,
    registration_end_date date         not null,
    start_date            date         not null,
    status                varchar(255) not null,
    primary key (id)
);
create table lessons
(
    id            int8 generated by default as identity,
    description   varchar(2048) not null,
    is_published  boolean       not null,
    name          varchar(255)  not null,
    internship_id int8,
    primary key (id)
);
create table task_solutions
(
    id               int8 generated by default as identity,
    checked_time     timestamp,
    comment          varchar(1024),
    last_commit_time timestamp    not null,
    last_commit_url  varchar(255) not null,
    repository_url   varchar(255) not null,
    status           varchar(255) not null,
    task_id          int8,
    user_id          int8,
    primary key (id)
);
create table tasks
(
    id            int8 generated by default as identity,
    description   varchar(2048) not null,
    name          varchar(255)  not null,
    publish_date  date,
    repository    varchar(255)  not null,
    repository_id int8          not null,
    lesson_id     int8,
    primary key (id)
);
create table users
(
    id            int8 generated by default as identity,
    email         varchar(255) not null,
    name          varchar(255) not null,
    password      varchar(255) not null,
    role          varchar(255),
    username      varchar(255) not null,
    internship_id int8,
    primary key (id)
);
alter table if exists applications
    add constraint applications_username_uk unique (username);
alter table if exists task_solutions
    add constraint repository_url_uk unique (repository_url);
alter table if exists users
    add constraint email_uk unique (email);
alter table if exists users
    add constraint users_username_uk unique (username);
alter table if exists applications
    add constraint applications_internships_fk foreign key (internship_id) references internships;
alter table if exists lessons
    add constraint lessons_internships_fk foreign key (internship_id) references internships;
alter table if exists task_solutions
    add constraint task_solutions_tasks_fk foreign key (task_id) references tasks;
alter table if exists task_solutions
    add constraint task_solutions_users_fk foreign key (user_id) references users;
alter table if exists tasks
    add constraint tasks_lessons_fk foreign key (lesson_id) references lessons;
alter table if exists users
    add constraint users_internships_fk foreign key (internship_id) references internships;
