create table application
(
    id               int8 generated by default as identity,
    about            varchar(255),
    birth_date       date         not null,
    city             varchar(255) not null,
    course           int4,
    education_status varchar(255) not null,
    email            varchar(255) not null,
    faculty          varchar(255),
    full_name        varchar(255) not null,
    phone_number     varchar(255) not null,
    specialty        varchar(255),
    status           varchar(255) not null,
    telegram_id      varchar(255) not null,
    university       varchar(255),
    username         varchar(255) not null,
    internship_id    int8,
    primary key (id)
);
create table internship
(
    id                    int8 generated by default as identity,
    description           varchar(255),
    end_date              date         not null,
    name                  varchar(255) not null,
    registration_end_date date         not null,
    start_date            date         not null,
    status                varchar(255) not null,
    primary key (id)
);
create table lesson
(
    id            int8 generated by default as identity,
    description   varchar(2048) not null,
    is_published  boolean       not null,
    name          varchar(255)  not null,
    internship_id int8,
    primary key (id)
);
create table task_solution
(
    id               int8 generated by default as identity,
    checked_time     timestamp,
    comment          varchar(1024),
    last_commit_time timestamp    not null,
    last_commit_url  varchar(255) not null,
    repository_url   varchar(255) not null,
    status           varchar(255) not null,
    task_id          int8,
    user_id          int8,
    primary key (id)
);
create table task
(
    id            int8 generated by default as identity,
    description   varchar(2048) not null,
    name          varchar(255)  not null,
    publish_date  date,
    repository    varchar(255)  not null,
    repository_id int8          not null,
    lesson_id     int8,
    primary key (id)
);
create table app_user
(
    id            int8 generated by default as identity,
    email         varchar(255) not null,
    name          varchar(255) not null,
    password      varchar(255) not null,
    role          varchar(255),
    username      varchar(255) not null,
    internship_id int8,
    primary key (id)
);
alter table if exists application
    add constraint application_username_uk unique (username);
alter table if exists task_solution
    add constraint repository_url_uk unique (repository_url);
alter table if exists app_user
    add constraint user_email_uk unique (email);
alter table if exists app_user
    add constraint user_username_uk unique (username);
alter table if exists application
    add constraint application_internship_fk foreign key (internship_id) references internship;
alter table if exists lesson
    add constraint lesson_internship_fk foreign key (internship_id) references internship;
alter table if exists task_solution
    add constraint task_solution_task_fk foreign key (task_id) references task;
alter table if exists task_solution
    add constraint task_solution_user_fk foreign key (user_id) references app_user;
alter table if exists task
    add constraint task_lesson_fk foreign key (lesson_id) references lesson;
alter table if exists app_user
    add constraint user_internship_fk foreign key (internship_id) references internship;
