CREATE TABLE IF NOT EXISTS messages
(
    id          INT8 GENERATED BY DEFAULT AS IDENTITY,
    text        VARCHAR(1024) NOT NULL,
    sent_at     TIMESTAMP     NOT NULL,
    receiver_id INT8,
    sender_id   INT8,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS messages
    ADD CONSTRAINT message_receiver_fk FOREIGN KEY (receiver_id) REFERENCES users,
    ADD CONSTRAINT message_sender_fk FOREIGN KEY (sender_id) REFERENCES users;